### PR TITLE
Fix platform_name option

### LINKED ISSUE #110: Unable to Add Platform
I am getting this error when ever i am trying to add a platform by 

`plugman platform add --platform_name android`

```
(node:17948) UnhandledPromiseRejectionWarning: Error: platform: true not yet supported
    at Object.add (E:\cordova-plugman\node_modules\cordova-lib\src\plugman\platform.js:51:35)
    at Object.module.exports [as platform] (E:\cordova-plugman\node_modules\cordova-lib\src\plugman\platform_operation.js:23:38)
    at Object.platform (E:\cordova-plugman\node_modules\cordova-lib\src\plugman\plugman.js:153:17)
    at Object.<anonymous> (E:\cordova-plugman\main.js:87:42)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
(node:17948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### PR DESCRIPTION
**Pull request by raphinesse**
Fixes #110

### CODE REVIEW

**Comment by erisu** [comment]
There is one question I had on something I ran into.

The command blow works as expected.
```
$ npx plugman install --platform ios --project ./ --plugin cordova-plugin-camera
Installing "cordova-plugin-camera" for ios
```

Is it expected for `--platform` and `--platform_name` is an interchangeable argument?

For example, should this command work?
```
$ npx plugman install --platform_name ios --project ./ --plugin cordova-plugin-camera
```
Currently the command above will fail.

Per the help printout from plugman, it appears that the `platform_name` argument is strictly for `plugman platform add` and `plugman platform remove`. If this is expected then I am OK with the PR.

**Comment by raphinesse** [comment]
@erisu Thanks for the review.

It is like you state in your last paragraph. The `platform_name` option is only used in the `platform` sub-command.

**Comment by elmorgan3** [comment]
Hello, I installed that plugin on Monday, but it didn't work, until I saw that change on this pull request. But there are not published yet, in npm. I had to change it, to make it work. I don't know if you know it, but I wanted to communicate it.

**Comment by raphinesse** [comment]
@elmorgan3 Yes, this fix is not released yet. Since our release process is a bit time consuming, I was hoping to get a few other fixes (#113) merged before we start preparing a patch release.

**Comment by elmorgan3** [comment]
Hi @monica18p, you need to modify main.js after install plugaman, with the code there are on last pull-request done [https://github.com/raphinesse/cordova-plugman/blob/cfe3dfc8b84410a94483488dcfa92746e514ba19/main.js](url). 
In my computer the plugin is installed on root "AppData/Roaming/npm/node_modules/plugman/main.js"
I hope that's help you.

**Comment by monica18p** [comment]
@raphinesse Noted. Can you please suggest any stable solution?

@elmorgan3 After updating main.js, package.json is being created a little weird. it takes id as "true" by its own
```
{
  "name": "cordovaPluginXXX",
  "version": "1.0.0",
  "description": "XXX plugin",
  "cordova": {
    "id": "true",
    "platforms": [
      "ios",
      "android"
    ]
  },
  "keywords": [
    "ecosystem:cordova",
    "cordova-ios",
    "cordova-android"
  ],
  "author": "XXX",
  "license": "ISC"
}
```

**Comment by raphinesse** [comment]
@monica18p The "stable" solution would be waiting for the next official release. In the meantime, I can give you my personal opinion that right now, `master` is probably more stable than the current release.

I believe that the second bug you encountered should be fixed by #113 (more specifically https://github.com/apache/cordova-plugman/commit/6410354ec558b9dd98243e3c4dc6630598dcd6f9) once that is merged and released. If you want to verify that your problem is fixed by that PR, you can install that version via `npm i -g raphinesse/cordova-plugman#fix-orgy`.

**Comment by monica18p** [comment]
But master is not able to add platforms.. For that need a stable solution.. but never mind will keep a watch on new release,, for now I have updated main.js as suggested by @elmorgan3 

Thanks.

**Pull request merged**
